(ns coldnew.compiler.brainfuck.backend.python
  (:require [clojure.pprint :refer [cl-format]]
            [clojure.string :as str]))

(declare generate-runtime ir->code)

(defn ir->python
  ([ir] (ir->python ir 3000))
  ([ir num-cells]
   (generate-runtime num-cells (apply str (map ir->code ir)))))

(defn generate-runtime
  [num-cells body]
  (cl-format nil "#!/usr/bin/env python
# This file is generated by coldnew's brainfuck compiler
# You can use following command to compile it:
#
#    python xxx.py
#
from __future__ import print_function

if __name__ == '__main__':
\tcells = [0] * ~d
\tptr = 0

~d

" num-cells body))


(defmulti ir->code (fn [ir] (:op ir)))

(defmethod ir->code :default
  [ir]
  (throw (ex-info "Unknown IR found " {:ir ir})))

(defmethod ir->code :add
  [ir]
  (let [indent (apply str (repeat (:indent-depth ir) "\t"))]
    (str indent "cells[ptr] += 1" "\n")))

(defmethod ir->code :sub
  [ir]
  (let [indent (apply str (repeat (:indent-depth ir) "\t"))]
    (str indent "cells[ptr] -= 1" "\n")))

(defmethod ir->code :right
  [ir]
  (let [indent (apply str (repeat (:indent-depth ir) "\t"))]
    (str indent "ptr += 1" "\n")))

(defmethod ir->code :left
  [ir]
  (let [indent (apply str (repeat (:indent-depth ir) "\t"))]
    (str indent "ptr -= 1" "\n")))

(defmethod ir->code :output
  [ir]
  (let [indent (apply str (repeat (:indent-depth ir) "\t"))]
    (str indent "print(chr(cells[ptr]), end='')" "\n")))

(defmethod ir->code :input
  [ir]
  (let [indent (apply str (repeat (:indent-depth ir) "\t"))]
    (str indent "int(input(\"Input = \"))" "\n")))

(defmethod ir->code :loop
  [ir]
  (let [indent (apply str (repeat (:indent-depth ir) "\t"))]
    (str indent "while cells[ptr] != 0:" "\n"
         indent (str/join indent (map ir->code (:children ir)))
         indent "\n")))

;;;; Extended IR (for optimize)

(defmethod ir->code :set-cell-value
  [ir]
  (let [indent (apply str (repeat (:indent-depth ir) "\t"))]
    (str indent "cells[ptr] += " (:val ir) "\n")))

(defmethod ir->code :set-cell-pointer
  [ir]
  (let [indent (apply str (repeat (:indent-depth ir) "\t"))]
    (str indent "ptr += " (:val ir) "\n")))

(defmethod ir->code :clear
  [ir]
  (let [indent (apply str (repeat (:indent-depth ir) "\t"))]
    (str indent "cells[ptr] = 0" "\n")))